### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.api'

### ISSUE THREAD

**Issue by dinarakhay** [Accenture/AIR#6]
When I ran ` !/bin/bash convert-model.sh` in Google Colab, it resulted in:

```
2022-03-22 09:32:42.586979: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
Traceback (most recent call last):
  File "keras_retinanet/keras_retinanet/bin/convert_model.py", line 103, in <module>
    main()
  File "keras_retinanet/keras_retinanet/bin/convert_model.py", line 79, in main
    model = models.load_model(args.model_in, backbone_name=args.backbone)
  File "keras_retinanet/keras_retinanet/bin/../../keras_retinanet/models/__init__.py", line 87, in load_model
    return keras.models.load_model(filepath, custom_objects=backbone(backbone_name).custom_objects, compile=compile)
  File "keras_retinanet/keras_retinanet/bin/../../keras_retinanet/models/__init__.py", line 57, in backbone
    from .resnet import ResNetBackbone as b
  File "keras_retinanet/keras_retinanet/bin/../../keras_retinanet/models/resnet.py", line 18, in <module>
    from keras.utils import get_file
ImportError: cannot import name 'get_file' from 'keras.utils' (/usr/local/lib/python3.7/dist-packages/keras/utils/__init__.py)
```

After some googling I found out that I should install kashgari, so I ran 

`pip install kashgari`

And when I came back to ` !/bin/bash convert-model.sh`, I had:

```
Using TensorFlow backend.
Traceback (most recent call last):
  File "keras_retinanet/keras_retinanet/bin/convert_model.py", line 33, in <module>
    from ..utils.config import read_config_file, parse_anchor_parameters
  File "keras_retinanet/keras_retinanet/bin/../../keras_retinanet/utils/config.py", line 19, in <module>
    import keras
  File "/usr/local/lib/python3.7/dist-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/__init__.py", line 26, in <module>
    from .vis_utils import model_to_dot
  File "/usr/local/lib/python3.7/dist-packages/keras/utils/vis_utils.py", line 7, in <module>
    from ..models import Model
  File "/usr/local/lib/python3.7/dist-packages/keras/models.py", line 12, in <module>
    from .engine.training import Model
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/__init__.py", line 8, in <module>
    from .training import Model
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training.py", line 14, in <module>
    from . import training_utils
  File "/usr/local/lib/python3.7/dist-packages/keras/engine/training_utils.py", line 17, in <module>
    from .. import metrics as metrics_module
  File "/usr/local/lib/python3.7/dist-packages/keras/metrics.py", line 1850, in <module>
    BaseMeanIoU = tf.keras.metrics.MeanIoU
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 58, in __getattr__
    module = self._load()
  File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/lazy_loader.py", line 41, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'keras.api'
```

Am I doing something wrong? Is there a way to address this error?

**Comment by Hyper5phere** [comment]
Hi,

I don't think [kashgari](https://pypi.org/project/kashgari/) (an NLP framework) has anything to do with the AIR detector, so I suggest you uninstall it from your current Python environment to avoid any module name conflicts.

The first error `CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected` suggests that you're either running on a CPU machine or your CUDA installation is somehow misconfigured. I recommend trying the CPU build/container of the AIR-detector and trying to run the `convert-model.sh` script again. Alternatively, you can play with your CUDA settings, but it can be difficult in a restricted Google Colab environment.

Lastly, maybe it's just about the `CUDA_VISIBLE_DEVICES` environment variable not being properly set, in which case running something like

```bash
CUDA_VISIBLE_DEVICES=0 /bin/bash convert-model.sh
```

might do the trick for you.
